services:
  # Configuración de tu aplicación Flask
  - type: web
    name: control-horario-superpekes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: control-horario
          property: connectionString

# Configuración de la base de datos PostgreSQL
databases:
  - name: control-horario
    plan: free # Nivel gratuitoco